### ISSUE TITLE
Errors building Android examples

### ISSUE THREAD

**Issue by ThorstenBux** [artoolkitx/artoolkit5#116]
<a href="https://github.com/carlonluca"><img src="https://avatars0.githubusercontent.com/u/3678828?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [carlonluca](https://github.com/carlonluca)**
_Friday Nov 03, 2017 at 17:51 GMT_
_Originally opened as https://github.com/artoolkit/artoolkit5/issues/353_

----

I'm trying to build Android examples using the build_native_examples.sh but I see a few build errors. For instance I see this:

```
jni/nftBook.cpp:364:26: error: use of undeclared identifier 'AR_VIDEO_PARAM_ANDROID_WIDTH'
        ar2VideoSetParami(gVid, AR_VIDEO_PARAM_ANDROID_WIDTH, videoWidth);
                                ^
jni/nftBook.cpp:364:26: error: use of undeclared identifier 'AR_VIDEO_PARAM_ANDROID_WIDTH'
        ar2VideoSetParami(gVid, AR_VIDEO_PARAM_ANDROID_WIDTH, videoWidth);
                                ^
jni/nftBook.cpp:364:26: error: use of undeclared identifier 'AR_VIDEO_PARAM_ANDROID_WIDTH'
        ar2VideoSetParami(gVid, AR_VIDEO_PARAM_ANDROID_WIDTH, videoWidth);
                                ^
jni/nftBook.cpp:364:26: error: use of undeclared identifier 'AR_VIDEO_PARAM_ANDROID_WIDTH'
        ar2VideoSetParami(gVid, AR_VIDEO_PARAM_ANDROID_WIDTH, videoWidth);
                                ^
jni/nftBook.cpp:365:26: error: use of undeclared identifier 'AR_VIDEO_PARAM_ANDROID_HEIGHT'
        ar2VideoSetParami(gVid, AR_VIDEO_PARAM_ANDROID_HEIGHT, videoHeight);
                                ^
jni/nftBook.cpp:365:26: error: use of undeclared identifier 'AR_VIDEO_PARAM_ANDROID_HEIGHT'
        ar2VideoSetParami(gVid, AR_VIDEO_PARAM_ANDROID_HEIGHT, videoHeight);
                                ^
jni/nftBook.cpp:365:26: error: use of undeclared identifier 'AR_VIDEO_PARAM_ANDROID_HEIGHT'
        ar2VideoSetParami(gVid, AR_VIDEO_PARAM_ANDROID_HEIGHT, videoHeight);
                                ^
jni/nftBook.cpp:365:26: error: use of undeclared identifier 'AR_VIDEO_PARAM_ANDROID_HEIGHT'
        ar2VideoSetParami(gVid, AR_VIDEO_PARAM_ANDROID_HEIGHT, videoHeight);
                                ^
jni/nftBook.cpp:366:26: error: use of undeclared identifier 'AR_VIDEO_PARAM_ANDROID_PIXELFORMAT'
        ar2VideoSetParami(gVid, AR_VIDEO_PARAM_ANDROID_PIXELFORMAT, (int)gPixFormat);
                                ^
jni/nftBook.cpp:366:26: error: use of undeclared identifier 'AR_VIDEO_PARAM_ANDROID_PIXELFORMAT'
        ar2VideoSetParami(gVid, AR_VIDEO_PARAM_ANDROID_PIXELFORMAT, (int)gPixFormat);
                                ^
jni/nftBook.cpp:366:26: error: use of undeclared identifier 'AR_VIDEO_PARAM_ANDROID_PIXELFORMAT'
        ar2VideoSetParami(gVid, AR_VIDEO_PARAM_ANDROID_PIXELFORMAT, (int)gPixFormat);
                                ^
jni/nftBook.cpp:366:26: error: use of undeclared identifier 'AR_VIDEO_PARAM_ANDROID_PIXELFORMAT'
        ar2VideoSetParami(gVid, AR_VIDEO_PARAM_ANDROID_PIXELFORMAT, (int)gPixFormat);
                                ^
```

Were these enums removed? I see occurrences only in the examples.

**Comment by ThorstenBux** [comment]
done: https://github.com/artoolkitx/artoolkit5/pull/6
@carlonluca

**Comment by southrop** [comment]
Hi, was this issue actually resolved? Unfortunately I still get a bunch of errors when trying to build the native examples using either `build_native_examples.sh` or directly trying to run `ndk-build.cmd` in the project directory. I'm not a C++ developer so I'm not too familiar with this, but I think they all look like missing declarations in a shared header/library? Error logs from the shell script are at the bottom.

On a related note, I think this git repository is actually missing a `libutil.a` file inside `android/obj/local/`. When I first tried to build, I got this error, but I was able to find a `libutil.a` from the old SDK package on the artoolkit.org website (`ARToolKit5-bin-5.3.2-Android.zip`).

```
Android NDK: ERROR:D:/Projects/SDK/artoolkit5/AndroidStudioProjects/nftSimpleProj/nftSimple/src/main/jni/Android.mk:util: LOCAL_SRC_FILES points to a missing file
Android NDK: Check that D:/Projects/SDK/artoolkit5/AndroidStudioProjects/nftSimpleProj/nftSimple/src/main/jni/../../../../../../android/obj/local/armeabi-v7a/libutil.a exists  or that its path is correct
C:/Users/admin/AppData/Local/Android/sdk/ndk-bundle/build//../build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.
```

---
**Shell script errors**

aRSimpleNative
```
jni/ARWrapperNativeExample.cpp:77: error: undefined reference to 'glStateCacheFlush'
jni/ARWrapperNativeExample.cpp:131: error: undefined reference to 'glStateCacheEnableDepthTest'
jni/ARWrapperNativeExample.cpp:132: error: undefined reference to 'glStateCacheDisableLighting'
jni/ARWrapperNativeExample.cpp:133: error: undefined reference to 'glStateCacheDisableTex2D'
jni/ARWrapperNativeExample.cpp:101: error: undefined reference to 'glStateCacheDisableLighting'
jni/ARWrapperNativeExample.cpp:102: error: undefined reference to 'glStateCacheDisableTex2D'
jni/ARWrapperNativeExample.cpp:103: error: undefined reference to 'glStateCacheDisableBlend'
jni/ARWrapperNativeExample.cpp:106: error: undefined reference to 'glStateCacheEnableClientStateVertexArray'
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [obj/local/armeabi-v7a/libARWrapperNativeExample.so] Error 1
```

aRSimpleNativeCars
```
jni/ARWrapperNativeCarsExample.cpp:119: error: undefined reference to 'glStateCacheFlush'
jni/ARWrapperNativeCarsExample.cpp:144: error: undefined reference to 'glStateCacheEnableDepthTest'
jni/ARWrapperNativeCarsExample.cpp:145: error: undefined reference to 'glStateCacheEnableLighting'
jni/../../lib/SRC/Eden/glm.c:2579: error: undefined reference to 'glStateCacheBlendFunc'
jni/../../lib/SRC/Eden/glm.c:2580: error: undefined reference to 'glStateCacheEnableBlend'
jni/../../lib/SRC/Eden/glm.c:2577: error: undefined reference to 'glStateCacheDisableBlend'
jni/../../lib/SRC/Eden/glm.c:2587: error: undefined reference to 'glStateCacheEnableClientStateVertexArray'
jni/../../lib/SRC/Eden/glm.c:2590: error: undefined reference to 'glStateCacheEnableClientStateNormalArray'
jni/../../lib/SRC/Eden/glm.c:2592: error: undefined reference to 'glStateCacheDisableClientStateNormalArray'
jni/../../lib/SRC/Eden/glm.c:2594: error: undefined reference to 'glStateCacheClientActiveTexture'
jni/../../lib/SRC/Eden/glm.c:2597: error: undefined reference to 'glStateCacheEnableClientStateTexCoordArray'
jni/../../lib/SRC/Eden/glm.c:2599: error: undefined reference to 'glStateCacheDisableClientStateTexCoordArray'
jni/../../lib/SRC/Eden/glm.c:2613: error: undefined reference to 'glStateCacheActiveTexture'
jni/../../lib/SRC/Eden/glm.c:2617: error: undefined reference to 'glStateCacheEnableTex2D'
jni/../../lib/SRC/Eden/glm.c:2617: error: undefined reference to 'glStateCacheDisableTex2D'
jni/../../lib/SRC/Eden/EdenSurfaces.c:132: error: undefined reference to 'glStateCachePixelStoreUnpackAlignment'
jni/../../lib/SRC/Eden/EdenSurfaces.c:178: error: undefined reference to 'glStateCacheActiveTexture'
jni/../../lib/SRC/Eden/EdenSurfaces.c:179: error: undefined reference to 'glStateCacheBindTexture2D'
jni/../../lib/SRC/Eden/EdenSurfaces.c:316: error: undefined reference to 'glStateCacheActiveTexture'
jni/../../lib/SRC/Eden/EdenSurfaces.c:317: error: undefined reference to 'glStateCacheBindTexture2D'
jni/../../lib/SRC/Eden/EdenSurfaces.c:318: error: undefined reference to 'glStateCacheTexEnvMode'
jni/../../lib/SRC/Eden/EdenSurfaces.c:330: error: undefined reference to 'glStateCacheActiveTexture'
jni/../../lib/SRC/Eden/EdenSurfaces.c:331: error: undefined reference to 'glStateCacheBindTexture2D'
jni/../../lib/SRC/Eden/EdenSurfaces.c:393: error: undefined reference to 'glStateCacheEnableClientStateVertexArray'
jni/../../lib/SRC/Eden/EdenSurfaces.c:395: error: undefined reference to 'glStateCacheEnableClientStateNormalArray'
jni/../../lib/SRC/Eden/EdenSurfaces.c:396: error: undefined reference to 'glStateCacheClientActiveTexture'
jni/../../lib/SRC/Eden/EdenSurfaces.c:398: error: undefined reference to 'glStateCacheEnableClientStateTexCoordArray'
jni/../../lib/SRC/Eden/EdenSurfaces.c:400: error: undefined reference to 'glStateCacheBindTexture2D'
jni/../../lib/SRC/Eden/EdenSurfaces.c:401: error: undefined reference to 'glStateCacheTexEnvMode'
jni/../../lib/SRC/Eden/EdenSurfaces.c:402: error: undefined reference to 'glStateCacheEnableTex2D'
jni/../../lib/SRC/Eden/EdenUtil.c:102: error: undefined reference to 'tcgetattr'
jni/../../lib/SRC/Eden/EdenUtil.c:107: error: undefined reference to 'tcsetattr'
jni/../../lib/SRC/Eden/EdenUtil.c:143: error: undefined reference to 'tcsetattr'
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [obj/local/x86/libARWrapperNativeCarsExample.so] Error 1
```

aRNativeES1
```
jni/ARNativeES1.cpp:346:26: error: use of undeclared identifier 'AR_VIDEO_PARAM_ANDROID_WIDTH'
        ar2VideoSetParami(gVid, AR_VIDEO_PARAM_ANDROID_WIDTH, videoWidth);
                                ^
jni/ARNativeES1.cpp:347:26: error: use of undeclared identifier 'AR_VIDEO_PARAM_ANDROID_HEIGHT'
        ar2VideoSetParami(gVid, AR_VIDEO_PARAM_ANDROID_HEIGHT, videoHeight);
                                ^
jni/ARNativeES1.cpp:348:26: error: use of undeclared identifier 'AR_VIDEO_PARAM_ANDROID_PIXELFORMAT'
        ar2VideoSetParami(gVid, AR_VIDEO_PARAM_ANDROID_PIXELFORMAT, (int)gPixFormat);
                                ^
jni/ARNativeES1.cpp:391:5: error: use of undeclared identifier 'arglCameraFrustumRHf'
    arglCameraFrustumRHf(&gCparamLT->param, NEAR_PLANE, FAR_PLANE, cameraLens);
    ^
jni/ARNativeES1.cpp:537:13: error: use of undeclared identifier 'arglCameraViewRHf'
            arglCameraViewRHf(markersSquare[i].trans, markersSquare[i].pose.T, 1.0f /*VIEW_SCALEFACTOR*/);
            ^
5 errors generated.
make: *** [obj/local/armeabi-v7a/objs/ARNativeES1/ARNativeES1.o] Error 1
```

aRNative
```
jni/ARNative.cpp:362:26: error: use of undeclared identifier 'AR_VIDEO_PARAM_ANDROID_WIDTH'
        ar2VideoSetParami(gVid, AR_VIDEO_PARAM_ANDROID_WIDTH, videoWidth);
                                ^
jni/ARNative.cpp:363:26: error: use of undeclared identifier 'AR_VIDEO_PARAM_ANDROID_HEIGHT'
        ar2VideoSetParami(gVid, AR_VIDEO_PARAM_ANDROID_HEIGHT, videoHeight);
                                ^
jni/ARNative.cpp:364:26: error: use of undeclared identifier 'AR_VIDEO_PARAM_ANDROID_PIXELFORMAT'
        ar2VideoSetParami(gVid, AR_VIDEO_PARAM_ANDROID_PIXELFORMAT, (int)gPixFormat);
                                ^
jni/ARNative.cpp:407:5: error: use of undeclared identifier 'arglCameraFrustumRHf'
    arglCameraFrustumRHf(&gCparamLT->param, NEAR_PLANE, FAR_PLANE, cameraLens);
    ^
jni/ARNative.cpp:553:13: error: use of undeclared identifier 'arglCameraViewRHf'
            arglCameraViewRHf(markersSquare[i].trans, markersSquare[i].pose.T, 1.0f /*VIEW_SCALEFACTOR*/);
            ^
5 errors generated.
make: *** [obj/local/armeabi-v7a/objs/ARNative/ARNative.o] Error 1
```

aRNativeOSG
```
jni/ARNativeOSG.cpp:350:26: error: use of undeclared identifier 'AR_VIDEO_PARAM_ANDROID_WIDTH'
        ar2VideoSetParami(gVid, AR_VIDEO_PARAM_ANDROID_WIDTH, videoWidth);
                                ^
jni/ARNativeOSG.cpp:351:26: error: use of undeclared identifier 'AR_VIDEO_PARAM_ANDROID_HEIGHT'
        ar2VideoSetParami(gVid, AR_VIDEO_PARAM_ANDROID_HEIGHT, videoHeight);
                                ^
jni/ARNativeOSG.cpp:352:26: error: use of undeclared identifier 'AR_VIDEO_PARAM_ANDROID_PIXELFORM                                                     AT'
        ar2VideoSetParami(gVid, AR_VIDEO_PARAM_ANDROID_PIXELFORMAT, (int)gPixFormat);
                                ^
jni/ARNativeOSG.cpp:395:5: error: use of undeclared identifier 'arglCameraFrustumRHf'
    arglCameraFrustumRHf(&gCparamLT->param, NEAR_PLANE, FAR_PLANE, cameraLens);
    ^
jni/ARNativeOSG.cpp:541:13: error: use of undeclared identifier 'arglCameraViewRHf'
            arglCameraViewRHf(markersSquare[i].trans, markersSquare[i].pose.T, 1.0f /*VIEW_SCALEF                                                     ACTOR*/);
            ^
[x86] Compile        : cpufeatures <= cpu-features.c
[armeabi-v7a] StaticLibrary  : libcpufeatures.a
jni/ARNativeOSG.cpp:350:26: error: use of undeclared identifier 'AR_VIDEO_PARAM_ANDROID_WIDTH'
        ar2VideoSetParami(gVid, AR_VIDEO_PARAM_ANDROID_WIDTH, videoWidth);
                                ^
jni/ARNativeOSG.cpp:351:26: error: use of undeclared identifier 'AR_VIDEO_PARAM_ANDROID_HEIGHT'
        ar2VideoSetParami(gVid, AR_VIDEO_PARAM_ANDROID_HEIGHT, videoHeight);
                                ^
jni/ARNativeOSG.cpp:352:26: error: use of undeclared identifier 'AR_VIDEO_PARAM_ANDROID_PIXELFORMAT'
        ar2VideoSetParami(gVid, AR_VIDEO_PARAM_ANDROID_PIXELFORMAT, (int)gPixFormat);
                                ^
jni/ARNativeOSG.cpp:395:5: error: use of undeclared identifier 'arglCameraFrustumRHf'
    arglCameraFrustumRHf(&gCparamLT->param, NEAR_PLANE, FAR_PLANE, cameraLens);
    ^
jni/ARNativeOSG.cpp:541:13: error: use of undeclared identifier 'arglCameraViewRHf'
            arglCameraViewRHf(markersSquare[i].trans, markersSquare[i].pose.T, 1.0f /*VIEW_SCALEFACTOR*/);
            ^
5 errors generated.
make: *** [obj/local/armeabi-v7a/objs/ARNativeOSGNative/ARNativeOSG.o] Error 1
```

nftSimple
```
jni/nftSimple.cpp:360:26: error: use of undeclared identifier 'AR_VIDEO_PARAM_ANDROID_WIDTH'
        ar2VideoSetParami(gVid, AR_VIDEO_PARAM_ANDROID_WIDTH, videoWidth);
                                ^
jni/nftSimple.cpp:361:26: error: use of undeclared identifier 'AR_VIDEO_PARAM_ANDROID_HEIGHT'
        ar2VideoSetParami(gVid, AR_VIDEO_PARAM_ANDROID_HEIGHT, videoHeight);
                                ^
jni/nftSimple.cpp:362:26: error: use of undeclared identifier 'AR_VIDEO_PARAM_ANDROID_PIXELFORMAT'
        ar2VideoSetParami(gVid, AR_VIDEO_PARAM_ANDROID_PIXELFORMAT, (int)gPixFormat);
                                ^
jni/nftSimple.cpp:403:2: error: use of undeclared identifier 'arglCameraFrustumRHf'
        arglCameraFrustumRHf(&gCparamLT->param, NEAR_PLANE, FAR_PLANE, cameraLens);
        ^
jni/nftSimple.cpp:670:13: error: use of undeclared identifier 'arglCameraViewRHf'
            arglCameraViewRHf(markersNFT[i].trans, markersNFT[i].pose.T, 1.0f /*VIEW_SCALEFACTOR*/);
            ^
```

nftBook
```
jni/nftBook.cpp:364:26: error: use of undeclared identifier 'AR_VIDEO_PARAM_ANDROID_WIDTH'
        ar2VideoSetParami(gVid, AR_VIDEO_PARAM_ANDROID_WIDTH, videoWidth);
                                ^
jni/nftBook.cpp:365:26: error: use of undeclared identifier 'AR_VIDEO_PARAM_ANDROID_HEIGHT'
        ar2VideoSetParami(gVid, AR_VIDEO_PARAM_ANDROID_HEIGHT, videoHeight);
                                ^
jni/nftBook.cpp:366:26: error: use of undeclared identifier 'AR_VIDEO_PARAM_ANDROID_PIXELFORMAT'
        ar2VideoSetParami(gVid, AR_VIDEO_PARAM_ANDROID_PIXELFORMAT, (int)gPixFormat);
                                ^
jni/nftBook.cpp:407:2: error: use of undeclared identifier 'arglCameraFrustumRHf'
        arglCameraFrustumRHf(&gCparamLT->param, NEAR_PLANE, FAR_PLANE, cameraLens);
        ^
jni/nftBook.cpp:674:13: error: use of undeclared identifier 'arglCameraViewRHf'
            arglCameraViewRHf(markersNFT[i].trans, markersNFT[i].pose.T, 1.0f /*VIEW_SCALEFACTOR*/);
            ^
```

aRMovie
```
jni/ARMovie.cpp:370:26: error: use of undeclared identifier 'AR_VIDEO_PARAM_ANDROID_WIDTH'
        ar2VideoSetParami(gVid, AR_VIDEO_PARAM_ANDROID_WIDTH, videoWidth);
                                ^
jni/ARMovie.cpp:371:26: error: use of undeclared identifier 'AR_VIDEO_PARAM_ANDROID_HEIGHT'
        ar2VideoSetParami(gVid, AR_VIDEO_PARAM_ANDROID_HEIGHT, videoHeight);
                                ^
jni/ARMovie.cpp:372:26: error: use of undeclared identifier 'AR_VIDEO_PARAM_ANDROID_PIXELFORMAT'
        ar2VideoSetParami(gVid, AR_VIDEO_PARAM_ANDROID_PIXELFORMAT, (int)gPixFormat);
                                ^
jni/ARMovie.cpp:415:2: error: use of undeclared identifier 'arglCameraFrustumRHf'
        arglCameraFrustumRHf(&gCparamLT->param, NEAR_PLANE, FAR_PLANE, cameraLens);
        ^
jni/ARMovie.cpp:684:13: error: use of undeclared identifier 'arglCameraViewRHf'
            arglCameraViewRHf(markersNFT[i].trans, markersNFT[i].pose.T, 1.0f /*VIEW_SCALEFACTOR*/);
            ^
5 errors generated.
```

calib_optical
```
jni/calib_optical.cpp:579:26: error: use of undeclared identifier 'AR_VIDEO_PARAM_ANDROID_WIDTH'
        ar2VideoSetParami(gVid, AR_VIDEO_PARAM_ANDROID_WIDTH, videoWidth);
                                ^
jni/calib_optical.cpp:580:26: error: use of undeclared identifier 'AR_VIDEO_PARAM_ANDROID_HEIGHT'
        ar2VideoSetParami(gVid, AR_VIDEO_PARAM_ANDROID_HEIGHT, videoHeight);
                                ^
jni/calib_optical.cpp:581:26: error: use of undeclared identifier 'AR_VIDEO_PARAM_ANDROID_PIXELFORMAT'
        ar2VideoSetParami(gVid, AR_VIDEO_PARAM_ANDROID_PIXELFORMAT, (int)gPixFormat);
                                ^
3 errors generated.
make: *** [obj/local/armeabi-v7a/objs/calib_optical_Native/calib_optical.o] Error 1
```

**Comment by ThorstenBux** [comment]
Hi @southrop, I'm sorry to say that, unfortunately, the native examples are broken. I welcome any contribution to fix this but at the moment only the examples using ARBaseLib work.

**Comment by southrop** [comment]
Thanks for the quick confirmation! Is it possible to implement NFT using ARBaseLib only? The only examples I can see based on NFT seem to be native.

**Comment by ThorstenBux** [comment]
change that line: https://github.com/artoolkitx/artoolkit5/blob/master/AndroidStudioProjects/ARSimpleProj/aRSimple/src/main/java/org/artoolkit/ar/samples/ARSimple/SimpleRenderer.java#L72

to `nft;data/nft/pinball` for example

https://github.com/artoolkitx/artoolkit5/blob/master/AndroidStudioProjects/ARBaseLibProj/aRBaseLib/src/main/java/org/artoolkit/ar/base/ARToolKit.java#L309
